from Constants import *

CONFIGURATION_NAME = "conf2"
ITERATIONS = 1000
MAX_TURNS = 1000
AGENT = QLEARNING
TASK = DETERMINISTIC
IS_IMMORTAL = False
MAP_SIZE = 5
BOMB_EXPLODING_PROBABILITY = 0.9
BOMB_REWARD_POLICY = BOMB_NO_REWARD
NAVIGATION_REWARD = NAVIGATION_NO_REWARD
WIN_REWARD = 10000.0
LOSE_REWARD = -10000.0
BOMB_REWARD = 10.0
