from Constants import *

CONFIGURATION_NAME = "RmaxBombReward"
ITERATIONS = 10000
MAX_TURNS = 1000
AGENT = RMAX
TASK = DETERMINISTIC
IS_IMMORTAL = False
MAP_SIZE = 5
BOMB_EXPLODING_PROBABILITY = 0.9
BOMB_REWARD_POLICY = BOMB_REWARD_PER_STONE_DESTROYED
NAVIGATION_REWARD = NAVIGATION_NO_REWARD
WIN_REWARD = 10000.0
LOSE_REWARD = -10000.0
BOMB_REWARD = 10.0
NO_ACTION_NEGATIVE_REWARD = True
INITIAL_REWARD = -1
USE_DELTABOMB_FACTOR = True

