# Bomb Rewards Policies
BOMB_NO_REWARD = 0
BOMB_REWARD_PER_STONE_DESTROYED = 1
BOMB_REWARD_PER_STONE_DESTROYED_PROPORTIONAL_TO_EXIT = 2

# Navigation Rewards Policies
NAVIGATION_NO_REWARD = 0
NAVIGATION_REWARD_PROPORTIONAL_TO_EXIT = 1

# Agents
QLEARNING = 0
RMAX = 1
FACTOREDRMAX = 2
FACTOREDAGENTS = [FACTOREDRMAX]

# Task
DETERMINISTIC = 0
STOCHASTIC_NAVIGATION = 1
STOCHASTIC_EXPLOSION = 2