from Settings import USE_DELTABOMB_FACTOR

class Factor:

	POSITION = 0
	BOMB = 1
	STONES = 2
	DEAD = 3
	DELTABOMB = 4

	FACTORS = [POSITION,BOMB,STONES,DEAD,DELTABOMB] if USE_DELTABOMB_FACTOR else [POSITION,BOMB,STONES,DEAD] 