
from Constants import *

CONFIGURATION_NAME = "QLEARNING"
ITERATIONS = 100000
MAX_TURNS = 10000
AGENT = QLEARNING
TASK = DETERMINISTIC
IS_IMMORTAL = False
MAP_SIZE = 8
BOMB_EXPLODING_PROBABILITY = 8.0
BOMB_REWARD_POLICY = 2 
NAVIGATION_REWARD = 1
WIN_REWARD = 10000.0
LOSE_REWARD = -10000.0
BOMB_REWARD = 100.0
USE_DELTABOMB_FACTOR = True

