from Constants import *

CONFIGURATION_NAME = "semanaCompu"
ITERATIONS = 1000
MAX_TURNS = 1000
#QLEARNING SARSA SARSALAMBDA DYNA
AGENT = DYNA
# STOCHASTIC_NAVIGATION  STOCHASTIC_EXPLOSION  
TASK = DETERMINISTIC
IS_IMMORTAL = False
MAP_SIZE = 8
BOMB_EXPLODING_PROBABILITY = 1.0
BOMB_REWARD_POLICY = 1
NAVIGATION_REWARD = 0
WIN_REWARD = 10000.0
LOSE_REWARD = -10000.0
BOMB_REWARD = 10.0
NO_ACTION_NEGATIVE_REWARD = True
INITIAL_REWARD = -1
USE_DELTABOMB_FACTOR = True
